config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  devise_scope :user do
    authenticated :user do
      root "users#show_profile", as: "show_profile_authed"
    end

    unauthenticated do
      root to: "devise/sessions#new"
    end
    
  end
  
  resources :permissions
  resources :roles, except: [:show] do
    resources :role_permissions, only: [:index, :create]
  end

  resources :departments
  
  scope "/manage" do
    resources :users
    get "/user/show_profile" => "users#show_profile", as: "show_profile"
    get "/user/edit_profile" => "users#edit_profile", as: "edit_profile"
    patch "/user/edit_profile" => "users#update_profile", as: "update_profile"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/permission.rb
# == Schema Information
#
# Table name: permissions
#
#  id          :bigint           not null, primary key
#  name        :string
#  resource    :string
#  action      :string
#  description :text
#  page        :boolean
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  slug        :string
#  deleted_at  :datetime
#
class Permission < ApplicationRecord
  extend FriendlyId
  friendly_id :slug_candidates, use: :slugged
  acts_as_paranoid

  validates :name,:resource,:action,:description,:path , presence: true

  #setting paginasi
  paginates_per 30


  #relasi antar table
  has_many :role_permissions
  #relasi untuk akses table ke permission tanpa harus menggunakan access_roles
  has_many :roles, through: :role_permissions
  #========================

  def self.check_resource_and_action(resource,action)
    self.where('resource = ?',resource).where('action = ?',action).first
  end
end

app/controllers/permissions_controller.rb
class PermissionsController < ApplicationController
  before_action :set_permission, only: [:show, :edit, :update, :destroy]

  # GET /permissions
  # GET /permissions.json
  def index
    @permissions = Permission.all
  end

  # GET /permissions/1
  # GET /permissions/1.json
  def show
  end

  # GET /permissions/new
  def new
    @permission = Permission.new
  end

  # GET /permissions/1/edit
  def edit
  end

  # POST /permissions
  # POST /permissions.json
  def create
    @permission = Permission.new(permission_params)

    respond_to do |format|
      if @permission.save
        format.html { redirect_to @permission, notice: 'Permission was successfully created.' }
        format.json { render :show, status: :created, location: @permission }
      else
        format.html { render :new }
        format.json { render json: @permission.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /permissions/1
  # PATCH/PUT /permissions/1.json
  def update
    respond_to do |format|
      if @permission.update(permission_params)
        format.html { redirect_to @permission, notice: 'Permission was successfully updated.' }
        format.json { render :show, status: :ok, location: @permission }
      else
        format.html { render :edit }
        format.json { render json: @permission.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /permissions/1
  # DELETE /permissions/1.json
  def destroy
    @permission.destroy
    respond_to do |format|
      format.html { redirect_to permissions_url, notice: 'Permission was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_permission
      @permission = Permission.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def permission_params
      params.require(:permission).permit(:name, :resource, :action, :description, :page)
    end
end

app/helpers/permissions_helper.rb
module PermissionsHelper
end

app/views/permissions/_form.html.erb
<%= form_with(model: permission) do |form| %>
  <%= render "error_messages", resource: form.object %>

<div class="row">
        <div class="col-md-6">
            <%= form.label :name, class: "label" %>
        <%= form.text_field :name, class: "input" %>
        </div>

        <div class="col-md-6">
            <%= form.label :resource, class: "label" %>
        <%= form.text_field :resource, class: "input" %>
        </div>

        <div class="col-md-6">
            <%= form.label :action, class: "label" %>
        <%= form.text_field :action, class: "input" %>
        </div>

        <div class="col-md-6">
            <%= form.label :description, class: "label" %>
        <%= form.text_area :description, class: "input" %>
        </div>

        <div class="col-md-6">
            <%= form.label :page, class: "label" %>
        <%= form.check_box :page, class: "input" %>
        </div>

        <div class="col-md-6 flex justify-between items-center">
        <%= form.button class: "btn btn-default" %>

        <% if form.object.persisted? %>
        <%= link_to 'Delete', form.object, class: "btn btn-default", method: :delete, data: { remote: true, confirm: "Are you sure?" } %>
        <% end %>
    </div>
</div>
<% end %>

app/views/permissions/edit.html.erb
<div class="container-fluid mt--6">
    <div class="row">
      <div class="col-lg-6">
        <div class="card-wrapper">
          <div class="card-header">
            <h3 class="mb-0">Editing Permission</h3>
          </div>

          <div class="card-body">
            <%= render 'form', permission: @permission %>
          </div>
        </div>
      </div>
    </div>
</div>

app/views/permissions/index.html.erb
<div class="container-fluid mt--6">
  <div class="row">
    <div class="col">
      <div class="card">
        <div class="card-header border-0">
          <div class="row">
            <div class="col-6">
              <h3 class="mb-0">Permissions</h3>
            </div>
            <div class="col-6 text-right">
              <% if @permissions.exists? %>
                <%= link_to new_permission, class: "btn btn-sm btn-neutral btn-round btn-icon" do %>
                          
                          <span>New</span>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
        <div class="table-responsive">
          <table class="table align-items-center table-flus">
            <thead class="thead-light">
              <tr>
                                  <th scope="col" class="sort">Name</th>
                                  <th scope="col" class="sort">Resource</th>
                                  <th scope="col" class="sort">Action</th>
                                  <th scope="col" class="sort">Description</th>
                                  <th scope="col" class="sort">Page</th>              </tr>
            </thead>
            <tbody>
              <% @permissions.each do |permission| %>
                <tr>
                                      <td><%= permission.name %></td>
                                      <td><%= permission.resource %></td>
                                      <td><%= permission.action %></td>
                                      <td><%= permission.description %></td>
                                      <td><%= permission.page %></td>
                  
                  <td>
                    <%= link_to "View", permission, class: "btn btn-default" %>
                    <%= link_to "Edit", edit_permission_path(permission), class: "btn btn-default" %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/permissions/new.html.erb
<div class="container-fluid mt--6">
    <div class="row">
      <div class="col-lg-6">
        <div class="card-wrapper">
          <div class="card-header">
            <h3 class="mb-0">New Permission</h3>
          </div>

          <div class="card-body">
            <%= render 'form', permission: @permission %>

            <%= link_to 'Back', permissions_path, class: "btn btn-neutral" %>
          </div>
        </div>
      </div>
    </div>
</div>

app/views/permissions/show.html.erb
<div class="container-fluid mt--6">
    <p class="text-lg font-semibold">Name:</p>
  <p class="leading-normal"><%= @permission.name %></p>

    <p class="text-lg font-semibold">Resource:</p>
  <p class="leading-normal"><%= @permission.resource %></p>

    <p class="text-lg font-semibold">Action:</p>
  <p class="leading-normal"><%= @permission.action %></p>

    <p class="text-lg font-semibold">Description:</p>
  <p class="leading-normal"><%= @permission.description %></p>

    <p class="text-lg font-semibold">Page:</p>
  <p class="leading-normal"><%= @permission.page %></p>

    <div class="flex items-center justify-start mt-6">
    <%= link_to 'Edit', edit_permission_path(@permission), class: "btn btn-default" %>
    <%= link_to 'Back', permissions_path, class: "btn btn-default" %>
  </div>
</div>