config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  devise_scope :user do
    authenticated :user do
      root "users#show_profile", as: "show_profile_authed"
    end

    unauthenticated do
      root to: "devise/sessions#new"
    end
    
  end
  
  resources :permissions
  resources :roles, except: [:show] do
    resources :role_permissions, only: [:index, :create]
  end

  resources :departments
  
  scope "/manage" do
    resources :users
    get "/user/show_profile" => "users#show_profile", as: "show_profile"
    get "/user/edit_profile" => "users#edit_profile", as: "edit_profile"
    patch "/user/edit_profile" => "users#update_profile", as: "update_profile"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/role_permission.rb
# == Schema Information
#
# Table name: role_permissions
#
#  id            :bigint           not null, primary key
#  role_id       :bigint           not null
#  permission_id :bigint           not null
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#
class RolePermission < ApplicationRecord
  belongs_to :permission
  belongs_to :role
  
  #untuk melakukan apakah access role memiliki data
  def self.check_status(role,permission)
      self.where('role_id = ?',role).where('permission_id = ?',permission).first
  end
  #=============

  #menghapus data access role data bahari berdasarkan role_id
  def self.destroy_oldrole(role)
      self.where('role_id = ?',role).destroy_all
  end
  #==============
end

app/controllers/role_permissions_controller.rb
class RolePermissionsController < ApplicationController
  before_action :set_role_permission, only: [:show, :edit, :update, :destroy]

  # GET /role_permissions
  # GET /role_permissions.json
  def index
    @role = Role.friendly.find(params[:role_id])
    # @role_permissions = RolePermission.where('role_id','=',@role)
    @role_permissions = @role.role_permissions
    
    p @role_permissions
    @permissions=Permission.all

    @role_permission = RolePermission.new
  end

  # GET /role_permissions/1
  # GET /role_permissions/1.json
  def show
  end

  # GET /role_permissions/new
  def new
    @role_permission = RolePermission.new
  end

  # GET /role_permissions/1/edit
  def edit
  end

  # POST /role_permissions
  # POST /role_permissions.json
  def create
    
    permissions=params[:permissions]
    role= Role.friendly.find(params[:role_id])
    deleteoldrole = RolePermission.destroy_oldrole(role)

    statussave=false

    permissions.each do |value|
      if value[1]=="1"
        permission = Permission.friendly.find(value[0])



        if !(RolePermission.check_status(role,permission))
          @access_role= RolePermission.new
          @access_role.role=role
          @access_role.permission=permission
          @access_role.save
        end

      end
    end
    #@role_permission = RolePermission.new(role_permission_params)

    #respond_to do |format|
      #if @role_permission.save
        #format.html { redirect_to @role_permission, notice: 'Role permission was successfully created.' }
        #format.json { render :show, status: :created, location: @role_permission }
      #else
        #format.html { render :new }
        #format.json { render json: @role_permission.errors, status: :unprocessable_entity }
      #end
    #end
  end

  # PATCH/PUT /role_permissions/1
  # PATCH/PUT /role_permissions/1.json
  def update
    respond_to do |format|
      if @role_permission.update(role_permission_params)
        format.html { redirect_to @role_permission, notice: 'Role permission was successfully updated.' }
        format.json { render :show, status: :ok, location: @role_permission }
      else
        format.html { render :edit }
        format.json { render json: @role_permission.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /role_permissions/1
  # DELETE /role_permissions/1.json
  def destroy
    @role_permission.destroy
    respond_to do |format|
      format.html { redirect_to role_permissions_url, notice: 'Role permission was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_role_permission
      @role_permission = RolePermission.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def role_permission_params
      params.fetch(:role_permission, {})
    end
end

app/helpers/role_permissions_helper.rb
module RolePermissionsHelper
end

app/views/role_permissions/_form.html.erb
<%= form_with(model: role_permission) do |form| %>
  <%= render "error_messages", resource: form.object %>

<div class="row">
        <div class="col-md-6 flex justify-between items-center">
        <%= form.button class: "btn btn-default" %>

        <% if form.object.persisted? %>
        <%= link_to 'Delete', form.object, class: "btn btn-default", method: :delete, data: { remote: true, confirm: "Are you sure?" } %>
        <% end %>
    </div>
</div>
<% end %>

app/views/role_permissions/edit.html.erb
<div class="container-fluid mt--6">
    <div class="row">
      <div class="col-lg-6">
        <div class="card-wrapper">
          <div class="card-header">
            <h3 class="mb-0">Editing Role Permission</h3>
          </div>

          <div class="card-body">
            <%= render 'form', role_permission: @role_permission %>
          </div>
        </div>
      </div>
    </div>
</div>

app/views/role_permissions/index.html.erb
 <h1>Role Name</h1>
<p><%= @role.name %></p>

<%= form_for [@role,@role_permission] do |form| %>

  <div class="actions">
    <%= form.submit %>
  </div>

  <table>
    <tbody>
      <% @permissions.group_by(&:resource).each do |resource_of,value| %>
        <tr>
          <th colspan="7" style="text-align:left"> Resource : <%= resource_of %></th>
        </tr>
        <tr>
          <th>#</th>
          <th>Name</th>
          <th>Action</th>
          <th>Page</th>
          <th>Description</th>
        </tr>
        <% @permissions.where('resource = ?',resource_of).each do |resource_of_permission| %>
          <tr>
            <% if RolePermission.check_status(@role.id,resource_of_permission.id) %>
              <td> <%= check_box("permissions", resource_of_permission.id, {checked: true}) %></td>
            <% else %>
              <td> <%= check_box("permissions", resource_of_permission.id, {checked: false}) %></td>
            <% end %>  
            <td><%= resource_of_permission.name %></td>
            <td><%= resource_of_permission.action %></td>
            <td><%= resource_of_permission.page %></td>
            <td><%= resource_of_permission.description %></td>
          </tr>
        <% end %>

            
          

      <% end %>
    </tbody>
  </table>

<% end %>
<br>

app/views/role_permissions/new.html.erb
<div class="container-fluid mt--6">
    <div class="row">
      <div class="col-lg-6">
        <div class="card-wrapper">
          <div class="card-header">
            <h3 class="mb-0">New Role Permission</h3>
          </div>

          <div class="card-body">
            <%= render 'form', role_permission: @role_permission %>

            <%= link_to 'Back', role_permissions_path, class: "btn btn-neutral" %>
          </div>
        </div>
      </div>
    </div>
</div>

app/views/role_permissions/show.html.erb
<div class="container-fluid mt--6">
    <div class="flex items-center justify-start mt-6">
    <%= link_to 'Edit', edit_role_permission_path(@role_permission), class: "btn btn-default" %>
    <%= link_to 'Back', role_permissions_path, class: "btn btn-default" %>
  </div>
</div>