config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  devise_scope :user do
    authenticated :user do
      root "users#show_profile", as: "show_profile_authed"
    end

    unauthenticated do
      root to: "devise/sessions#new"
    end
    
  end
  
  resources :permissions
  resources :roles, except: [:show] do
    resources :role_permissions, only: [:index, :create]
  end

  resources :departments
  
  scope "/manage" do
    resources :users
    get "/user/show_profile" => "users#show_profile", as: "show_profile"
    get "/user/edit_profile" => "users#edit_profile", as: "edit_profile"
    patch "/user/edit_profile" => "users#update_profile", as: "update_profile"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/role.rb
# == Schema Information
#
# Table name: roles
#
#  id         :bigint           not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  slug       :string
#  deleted_at :datetime
#
class Role < ApplicationRecord
  #include plugin paranoia dan friendly_id
  acts_as_paranoid

  extend FriendlyId
  friendly_id :slug_candidates, use: :slugged

  validates :name, presence: true
  
  #setting paginasi
  paginates_per 30

  has_many :role_permissions
  has_many :permissions, through: :role_permissions
  has_many :users
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :set_role, only: [:show, :edit, :update, :destroy]

  breadcrumb 'All Roles', :roles_path, only: [:new, :create, :edit, :update]

  # GET /roles
  # GET /roles.json
  def index
    @roles = Role.all
  end

  # GET /roles/1
  # GET /roles/1.json
  def show
  end

  # GET /roles/new
  def new
    @role = Role.new
  end

  # GET /roles/1/edit
  def edit
  end

  # POST /roles
  # POST /roles.json
  def create
    @role = Role.new(role_params)

    respond_to do |format|
      if @role.save
        format.html { redirect_to @role, notice: 'Role was successfully created.' }
        format.json { render :show, status: :created, location: @role }
      else
        format.html { render :new }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roles/1
  # PATCH/PUT /roles/1.json
  def update
    respond_to do |format|
      if @role.update(role_params)
        format.html { redirect_to @role, notice: 'Role was successfully updated.' }
        format.json { render :show, status: :ok, location: @role }
      else
        format.html { render :edit }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.json
  def destroy
    @role.destroy
    respond_to do |format|
      format.html { redirect_to roles_url, notice: 'Role was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_role
      @role = Role.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def role_params
      params.require(:role).permit(:name)
    end
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/roles/_form.html.erb
<%= form_with(model: role) do |form| %>
  <%= render "error_messages", resource: form.object %>

<div class="row">
        <div class="col-md-6">
            <%= form.label :name, class: "label" %>
        <%= form.text_field :name, class: "input" %>
        </div>

        <div class="col-md-6 flex justify-between items-center">
        <%= form.button class: "btn btn-default" %>

        <% if form.object.persisted? %>
        <%= link_to 'Delete', form.object, class: "btn btn-default", method: :delete, data: { remote: true, confirm: "Are you sure?" } %>
        <% end %>
    </div>
</div>
<% end %>

app/views/roles/edit.html.erb
<div class="container-fluid mt--6">
    <div class="row">
      <div class="col-lg-6">
        <div class="card-wrapper">
          <div class="card-header">
            <h3 class="mb-0">Editing Role</h3>
          </div>

          <div class="card-body">
            <%= render 'form', role: @role %>
          </div>
        </div>
      </div>
    </div>
</div>

app/views/roles/index.html.erb
<div class="container-fluid mt--6">
  <div class="row">
    <div class="col">
      <div class="card">
        <div class="card-header border-0">
          <div class="row">
            <div class="col-6">
              <h3 class="mb-0">Roles</h3>
            </div>
            <div class="col-6 text-right">
              <% if @roles.exists? %>
                <%= link_to new_role, class: "btn btn-sm btn-neutral btn-round btn-icon" do %>
                          
                          <span>New</span>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
        <div class="table-responsive">
          <table class="table align-items-center table-flus">
            <thead class="thead-light">
              <tr>
                                  <th scope="col" class="sort">Name</th>
                
              </tr>
            </thead>
            <tbody>
              <% @roles.each do |role| %>
                <tr>
                                      <td><%= role.name %></td>
                  
                  <td>
                    <%= link_to "View", role, class: "btn btn-default" %>
                    <%= link_to "Edit", edit_role_path(role), class: "btn btn-default" %>
                    <td>
                        <%= link_to role_role_permissions_path(role), class: "btn btn-icon btn-sm btn-success" do %>
                          <%= icon("fas","cogs", class: "text-white")%>
                        <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/roles/new.html.erb
<div class="container-fluid mt--6">
    <div class="row">
      <div class="col-lg-6">
        <div class="card-wrapper">
          <div class="card-header">
            <h3 class="mb-0">New Role</h3>
          </div>

          <div class="card-body">
            <%= render 'form', role: @role %>

            <%= link_to 'Back', roles_path, class: "btn btn-neutral" %>
          </div>
        </div>
      </div>
    </div>
</div>

app/views/roles/show.html.erb
<div class="container-fluid mt--6">
    <p class="text-lg font-semibold">Name:</p>
  <p class="leading-normal"><%= @role.name %></p>

    <div class="flex items-center justify-start mt-6">
    <%= link_to 'Edit', edit_role_path(@role), class: "btn btn-default" %>
    <%= link_to 'Back', roles_path, class: "btn btn-default" %>
  </div>
</div>